//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturuldu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeWeb.App.WebForm.Account {
    
    
    public partial class Login {
        
        /// <summary>
        /// ErrorMessage denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorMessage;
        
        /// <summary>
        /// FailureText denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal FailureText;
        
        /// <summary>
        /// Email control.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email;
        
        /// <summary>
        /// Password denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Password;
        
        /// <summary>
        /// RememberMe denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox RememberMe;
        
        /// <summary>
        /// RegisterHyperLink denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink RegisterHyperLink;
        
        /// <summary>
        /// OpenAuthLogin denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::PrimeWeb.App.WebForm.Account.OpenAuthProviders OpenAuthLogin;
    }
}
